## never manipulate tf datasets using map or other such functions except for batching, mapping, windowing,shuffling. Always manipulate data n convert to tensors n use tfds chaining funcs.

## ds.map should not use non tensorflow fnc...eg. using .numpy() causes error "AttributeError: 'SymbolicTensor' object has no attribute 'numpy'"
```
def fnc(ds_i):
  sn=ds_i['passage'].numpy().decode('UTF-8').split()
  return sn[:-1], sn[-1]
for item in train_set_sup.take(1):
  print(fnc(item))
list(train_set_sup.as_numpy_iterator())


ds=train_set_sup
# ds=train_set_sup.map(lambda it:tf.py_function(fun=fnc(it),inp=(1,),Tout=tf.float32))
# ds=train_set_sup.map(lambda it:it['passage'].numpy().decode('UTF-8').split())
ds=train_set_sup.map(fnc)


# for item in ds.take(1):
#   print(fnc(item))
```

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import tensorflow_datasets as tfds

In [ ]:
# (train_set_sup, valid_set_sup, test_set_sup), info_sup = tfds.load("cifar10",
#                                            split=["train[20%:]","train[0%:20%]","test" ],
#                                            as_supervised = True,with_info=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

In [4]:
# print(tf.executing_eagerly())


True


In [36]:
(train_set_sup_act, valid_set_sup, test_set_sup), info_sup = tfds.load("lambada",
                                           split=["train[20%:70%]","train[0%:10%]","train[10%:20%]" ],
                                           with_info=True)

In [37]:
len(train_set_sup_act),len(valid_set_sup),len(test_set_sup)

(2434, 487, 487)

In [38]:
train_set_sup=list(train_set_sup_act.take(1000))
len(train_set_sup)

1000

In [39]:
train_set_sup[:2]

[{'passage': <tf.Tensor: shape=(), dtype=string, numpy=b"the growling , the screaming , everything stopped . the air stank of decaying flesh and burnt hair . in the quiet stillness of his room , link froze , too scared to discover what awaited him in the lingering darkness . `` ayden ? '' he called . `` are you there ? '' 34 the face in the mirror link called out again , more urgently this time , `` ayden\n">},
 {'passage': <tf.Tensor: shape=(), dtype=string, numpy=b"scarlet let him pick , and he noticed she tried not to look at the price tag . one dress , he observed , she 'd paid particular attention to . richard chuckled as the tag was inspected . a blush , and then her eyes widened before she turned away . however , he hated seeing the yearning look she gave the piece . when the assistant took her into the dressing rooms , he went and checked out the dress\n">}]

In [40]:
# for item in train_set_sup.take(6):
#   print(item)
#   # print(type(item))

In [42]:
tr_ls=train_set_sup
tr_ls[:2]

[{'passage': <tf.Tensor: shape=(), dtype=string, numpy=b"the growling , the screaming , everything stopped . the air stank of decaying flesh and burnt hair . in the quiet stillness of his room , link froze , too scared to discover what awaited him in the lingering darkness . `` ayden ? '' he called . `` are you there ? '' 34 the face in the mirror link called out again , more urgently this time , `` ayden\n">},
 {'passage': <tf.Tensor: shape=(), dtype=string, numpy=b"scarlet let him pick , and he noticed she tried not to look at the price tag . one dress , he observed , she 'd paid particular attention to . richard chuckled as the tag was inspected . a blush , and then her eyes widened before she turned away . however , he hated seeing the yearning look she gave the piece . when the assistant took her into the dressing rooms , he went and checked out the dress\n">}]

In [43]:
def myfunc(it):
  return it['passage'].numpy().decode('UTF-8')

# x = map(myfunc, ('apple', 'banana', 'cherry'))


In [44]:
tr_np=list(map(myfunc,tr_ls))

In [45]:
len(tr_np)

1000

In [46]:
# tr_np=tr_ls['passage'].numpy()
tr_np[:2]

["the growling , the screaming , everything stopped . the air stank of decaying flesh and burnt hair . in the quiet stillness of his room , link froze , too scared to discover what awaited him in the lingering darkness . `` ayden ? '' he called . `` are you there ? '' 34 the face in the mirror link called out again , more urgently this time , `` ayden\n",
 "scarlet let him pick , and he noticed she tried not to look at the price tag . one dress , he observed , she 'd paid particular attention to . richard chuckled as the tag was inspected . a blush , and then her eyes widened before she turned away . however , he hated seeing the yearning look she gave the piece . when the assistant took her into the dressing rooms , he went and checked out the dress\n"]

In [47]:
def myfuncSplit(it):
  splitted=it.split()
  return splitted[:-1],splitted[-1]

# x = map(myfunc, ('apple', 'banana', 'cherry'))


In [48]:
tr_np_splt=list(map(myfuncSplit,tr_np))

In [49]:
# tr_np=tr_ls['passage'].numpy()
tr_np_splt[:2]

[(['the',
   'growling',
   ',',
   'the',
   'screaming',
   ',',
   'everything',
   'stopped',
   '.',
   'the',
   'air',
   'stank',
   'of',
   'decaying',
   'flesh',
   'and',
   'burnt',
   'hair',
   '.',
   'in',
   'the',
   'quiet',
   'stillness',
   'of',
   'his',
   'room',
   ',',
   'link',
   'froze',
   ',',
   'too',
   'scared',
   'to',
   'discover',
   'what',
   'awaited',
   'him',
   'in',
   'the',
   'lingering',
   'darkness',
   '.',
   '``',
   'ayden',
   '?',
   "''",
   'he',
   'called',
   '.',
   '``',
   'are',
   'you',
   'there',
   '?',
   "''",
   '34',
   'the',
   'face',
   'in',
   'the',
   'mirror',
   'link',
   'called',
   'out',
   'again',
   ',',
   'more',
   'urgently',
   'this',
   'time',
   ',',
   '``'],
  'ayden'),
 (['scarlet',
   'let',
   'him',
   'pick',
   ',',
   'and',
   'he',
   'noticed',
   'she',
   'tried',
   'not',
   'to',
   'look',
   'at',
   'the',
   'price',
   'tag',
   '.',
   'one',
   'dress',


In [50]:
type(tr_np_splt)

list

In [51]:
x_train_spl=[x for (x,y) in tr_np_splt]

In [52]:
x_train_spl[:2]

[['the',
  'growling',
  ',',
  'the',
  'screaming',
  ',',
  'everything',
  'stopped',
  '.',
  'the',
  'air',
  'stank',
  'of',
  'decaying',
  'flesh',
  'and',
  'burnt',
  'hair',
  '.',
  'in',
  'the',
  'quiet',
  'stillness',
  'of',
  'his',
  'room',
  ',',
  'link',
  'froze',
  ',',
  'too',
  'scared',
  'to',
  'discover',
  'what',
  'awaited',
  'him',
  'in',
  'the',
  'lingering',
  'darkness',
  '.',
  '``',
  'ayden',
  '?',
  "''",
  'he',
  'called',
  '.',
  '``',
  'are',
  'you',
  'there',
  '?',
  "''",
  '34',
  'the',
  'face',
  'in',
  'the',
  'mirror',
  'link',
  'called',
  'out',
  'again',
  ',',
  'more',
  'urgently',
  'this',
  'time',
  ',',
  '``'],
 ['scarlet',
  'let',
  'him',
  'pick',
  ',',
  'and',
  'he',
  'noticed',
  'she',
  'tried',
  'not',
  'to',
  'look',
  'at',
  'the',
  'price',
  'tag',
  '.',
  'one',
  'dress',
  ',',
  'he',
  'observed',
  ',',
  'she',
  "'d",
  'paid',
  'particular',
  'attention',
  'to',
  

In [53]:
len_x_spl=[len(i) for i in x_train_spl]
len_x_spl[:2]

[72, 81]

In [54]:
percntl_train_95=np.percentile(len_x_spl,95)
percntl_train_95

94.0

In [55]:
x_train_jn=[" ".join(x) for x in x_train_spl]

In [56]:
x_train_jn[:2]

["the growling , the screaming , everything stopped . the air stank of decaying flesh and burnt hair . in the quiet stillness of his room , link froze , too scared to discover what awaited him in the lingering darkness . `` ayden ? '' he called . `` are you there ? '' 34 the face in the mirror link called out again , more urgently this time , ``",
 "scarlet let him pick , and he noticed she tried not to look at the price tag . one dress , he observed , she 'd paid particular attention to . richard chuckled as the tag was inspected . a blush , and then her eyes widened before she turned away . however , he hated seeing the yearning look she gave the piece . when the assistant took her into the dressing rooms , he went and checked out the"]

In [57]:
vocab_size=68_000

In [58]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

In [59]:
tr_np

["the growling , the screaming , everything stopped . the air stank of decaying flesh and burnt hair . in the quiet stillness of his room , link froze , too scared to discover what awaited him in the lingering darkness . `` ayden ? '' he called . `` are you there ? '' 34 the face in the mirror link called out again , more urgently this time , `` ayden\n",
 "scarlet let him pick , and he noticed she tried not to look at the price tag . one dress , he observed , she 'd paid particular attention to . richard chuckled as the tag was inspected . a blush , and then her eyes widened before she turned away . however , he hated seeing the yearning look she gave the piece . when the assistant took her into the dressing rooms , he went and checked out the dress\n",
 "b1-but -- b2-i 'll delete your ` but ' from your arsebook if u do n't get tapping ! stop whining and get back to commenting ?! u know the stats : 73 % of all hits last month were the result of comments on other lifeblogs , so get com

In [60]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(tr_np)
total_words=len(tokenizer.word_index)+1
seq_zero_ind_corpus=tokenizer.texts_to_sequences([x_train_jn[0]])
print('total_words',total_words,'seq_zero_ind_corpus',seq_zero_ind_corpus)
print(type(tokenizer.word_index))

total_words 7897 seq_zero_ind_corpus [[1, 2414, 1, 3823, 237, 225, 1, 353, 3824, 7, 3825, 2415, 5, 3826, 354, 13, 1, 510, 3827, 7, 18, 137, 2416, 2417, 115, 1116, 2, 2418, 32, 3828, 30, 13, 1, 3829, 721, 2419, 3, 9, 254, 60, 8, 53, 3, 3830, 1, 116, 13, 1, 1365, 2416, 254, 35, 126, 80, 3831, 37, 71]]
<class 'dict'>


In [77]:
tokenizer.word_docs

defaultdict(int,
            {'flesh': 2,
             'more': 101,
             'and': 769,
             'called': 26,
             'stopped': 30,
             'room': 49,
             'froze': 2,
             'to': 832,
             '34': 1,
             'of': 626,
             'air': 18,
             'stillness': 1,
             'this': 215,
             'lingering': 1,
             'darkness': 8,
             'growling': 2,
             'quiet': 12,
             'scared': 5,
             'he': 480,
             'too': 66,
             'there': 157,
             'are': 132,
             'urgently': 1,
             'ayden': 1,
             'hair': 18,
             "''": 701,
             'the': 878,
             'mirror': 4,
             'decaying': 1,
             'again': 60,
             'in': 494,
             'face': 65,
             'out': 214,
             'discover': 2,
             'time': 107,
             'burnt': 1,
             'screaming': 1,
             'stank': 1,
  

In [83]:
for a in range(1,7):
  print(tokenizer.index_word[a])

the
to
''
i
and
a


In [85]:
print(tokenizer.oov_token)

None


In [62]:
li_seq=[]
li=[]
for cnt,line in enumerate(tr_np):
  seq=tokenizer.texts_to_sequences([line])
  seq_1dim_less=seq[0]
  li_seq.append(seq_1dim_less)
  maxlen=max([len(i) for i in li_seq])
  for i in range(1,len(seq_1dim_less)):
    li.append(seq_1dim_less[:i+1])

  # if(cnt<2):
    # print(len(seq_1dim_less))

    # print(cnt,line)
    # print(li_seq)
    # print(li)
    # print('maxlen',maxlen)

# pd_li=pad_sequences(li,maxlen=maxlen,padding='pre')

pd_li=pad_sequences(li,maxlen=int(percntl_train_95),padding='pre')
# percntl_train_95
print(pd_li[:5])
print(pd_li.shape)
xs=pd_li[:,:-1]
lbls=pd_li[:,-1]
xs_0=pd_li[0][:-1]
# lbls=pd_li[:,-1]
print(xs.shape)
print(xs[:5])
print(lbls.shape)
print(lbls[:5])
print('maxlen',maxlen)

ys=tf.keras.utils.to_categorical(lbls,num_classes=total_words)
print(ys.shape)
print(ys[:5])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    1 2414]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    1 2414    1]
 [   0    0    0    0    0    

In [63]:
xs[0],ys[0]

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1]),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32))

In [64]:
ys[0]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [65]:
xs[1],ys[1]


(array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    1, 2414]),
 array([0., 1., 0., ..., 0., 0., 0.], dtype=float32))

## error at fit b4, reason was input shape was,
Embedding(total_words,embedding_dim,input_length=maxlen-1)
blw model correction wrkd

return ops.EagerTensor(value, ctx.device_name, dtype)

InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.

In [66]:
embedding_dim=128
##%%
def create_model_seq():
  model=Sequential([
      # Embedding(total_words,embedding_dim,input_length=maxlen-1),
      Embedding(total_words,embedding_dim,input_length=int(percntl_train_95)-1),
      Bidirectional(LSTM(128)),
      Dense(total_words,activation='softmax')
      # Dense(64,activation='relu')
  ])
  return model
##%%
model=create_model_seq()
##%%
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
##%%
epochs=500
##%%
history=model.fit(xs,ys,epochs=epochs)

Epoch 1/500
1969/1969 [==============================] - 30s 14ms/step - loss: 6.6522 - accuracy: 0.0604
Epoch 2/500
1969/1969 [==============================] - 28s 14ms/step - loss: 5.8608 - accuracy: 0.1112
Epoch 3/500
1969/1969 [==============================] - 28s 14ms/step - loss: 5.3856 - accuracy: 0.1382
Epoch 4/500
1969/1969 [==============================] - 67s 34ms/step - loss: 5.0096 - accuracy: 0.1564
Epoch 5/500
1969/1969 [==============================] - 70s 35ms/step - loss: 4.6630 - accuracy: 0.1755
Epoch 6/500
1969/1969 [==============================] - 38s 19ms/step - loss: 4.3301 - accuracy: 0.1984
Epoch 7/500
1969/1969 [==============================] - 64s 33ms/step - loss: 4.0062 - accuracy: 0.2280
Epoch 8/500
1969/1969 [==============================] - 71s 36ms/step - loss: 3.6894 - accuracy: 0.2663
Epoch 9/500
1969/1969 [==============================] - 71s 36ms/step - loss: 3.3859 - accuracy: 0.3108
Epoch 10/500
1969/1969 [==============================]

KeyboardInterrupt: 

In [67]:
list(test_set_sup.take(1))

[{'passage': <tf.Tensor: shape=(), dtype=string, numpy=b"`` you all right ? '' `` i always do this with isabelle and jace , '' said alec . `` and they 're not here . and i ca n't call them . '' `` why not ? '' magnus asked . alec blushed just as magnus realized what he meant . alec could n't call his friends because he did n't want them to know he was on a date with magnus\n">}]

In [73]:
sample="`` you all right ? '' `` i always do this with isabelle and jace , '' said alec . `` and they 're not here . and i ca n't call them . '' `` why not ? '' magnus asked . alec blushed just as magnus realized what he meant . alec could n't call his friends because he did n't want them to know he was on a date with"

smp_li=sample.split()
len(smp_li)

73

In [74]:
inp_sample="`` you all right ? '' `` i always do this with isabelle and jace , '' said alec . `` and they 're not here . and i ca n't call them . '' `` why not ? '' magnus asked . alec blushed just as magnus realized what he meant . alec could n't call his friends because he did n't want them to know he was on a date with"

In [97]:
def next_char(inp_sample, temperature=1):
    inp_seq=tokenizer.texts_to_sequences([inp_sample])
    pd_inp_seq=pad_sequences(inp_seq,maxlen=int(percntl_train_95)-1,padding='pre')
    print(pd_inp_seq)
    y_proba=model.predict(pd_inp_seq)
    rescaled_logits = tf.math.log(y_proba) / temperature
    char_id = tf.random.categorical(rescaled_logits, num_samples=1)[0, 0]
    print(char_id.numpy())
    print(tokenizer.index_word[char_id.numpy()])

    return tokenizer.index_word[char_id.numpy()]

next_char(inp_sample, temperature=1)
next_char(inp_sample, temperature=0.1)
next_char(inp_sample, temperature=0.001)
next_char(inp_sample, temperature=0.5)

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    8   47   93    3    4  181
    28   37   21    5 1681    3   19 3045    5   38   78   39   86    5
     4  148   16  243   66    3  104   39    3   83 3045   58   23  465
    32    9  569 3045   51   16  243   18  405  147    9   40   16   91
    66    2   44    9   10   22    6  751   21]]
1/1 [==============================] - 0s 15ms/step
194
home
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    8   47   93    3    4  181
    28   37   21    5 1681    3   19 3045    5   38   78   39   86    5
     4  148   16  243   66    3  104   39    3   83 3045   58   23  465
    32    9  569 3045   51   16  243   18  405  147    9   40   16   91
    66    2   44    9   10

'home'

In [98]:
# Define seed text
seed_text = "`` you all right ? '' `` i always do this with isabelle and jace , '' said alec . `` and they 're not here . and i ca n't call them . '' `` why not ? '' magnus asked . alec blushed just as magnus realized what he meant . alec could n't call his friends because he did n't want them to know he was on a date with"

# Define total words to predict
next_words = 1

# Loop until desired length is reached
for _ in range(next_words):

	# Convert the seed text to a token sequence
  token_list = tokenizer.texts_to_sequences([seed_text])[0]

	# Pad the sequence
  token_list = pad_sequences([token_list], maxlen=maxlen-1, padding='pre')

	# Feed to the model and get the probabilities for each index
  probabilities = model.predict(token_list)

  # Pick a random number from [1,2,3]
  choice = np.random.choice([1,2,3])
  print(f'{choice=}')

  # Sort the probabilities in ascending order
  # and get the random choice from the end of the array
  predicted = np.argsort(probabilities)[0][-choice]
  print(f'{np.argsort(probabilities)[0]=}')
  print(f'{np.argsort(probabilities)[0][-choice]=}')

	# Ignore if index is 0 because that is just the padding.
  if predicted != 0:

		# Look up the word associated with the index.
	  output_word = tokenizer.index_word[predicted]

		# Combine with the seed text
	  seed_text += " " + output_word

# Print the result
print(seed_text)

1/1 [==============================] - 0s 290ms/step
choice=2
np.argsort(probabilities)[0]=array([1951, 5159, 7182, ...,    1,  194,   86], dtype=int64)
np.argsort(probabilities)[0][-choice]=194
`` you all right ? '' `` i always do this with isabelle and jace , '' said alec . `` and they 're not here . and i ca n't call them . '' `` why not ? '' magnus asked . alec blushed just as magnus realized what he meant . alec could n't call his friends because he did n't want them to know he was on a date with home


In [94]:
print(tokenizer.index_word[1])

the


In [93]:
print(tokenizer.index_word[194])

home


In [76]:
def next_word(inp_sample):
  inp_seq=tokenizer.texts_to_sequences([inp_sample])
  pd_inp_seq=pad_sequences(inp_seq,maxlen=int(percntl_train_95)-1,padding='pre')
  print(pd_inp_seq)
  y_proba=model.predict(pd_inp_seq)
  print('y_proba.shape',y_proba.shape)
  y_pred=np.argmax(y_proba,axis=-1)
  print('y_pred.shape',y_pred.shape)
  print('y_pred',y_pred)
  print('y_pred[0]',y_pred[0])
  # tf.random.categorical()
  nxt_w=tokenizer.index_word[y_pred[0]]
  return nxt_w

next_word(inp_sample)

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    8   47   93    3    4  181
    28   37   21    5 1681    3   19 3045    5   38   78   39   86    5
     4  148   16  243   66    3  104   39    3   83 3045   58   23  465
    32    9  569 3045   51   16  243   18  405  147    9   40   16   91
    66    2   44    9   10   22    6  751   21]]
1/1 [==============================] - 0s 18ms/step
y_proba.shape (1, 7897)
y_pred.shape (1,)
y_pred [194]
y_pred[0] 194


'home'

In [ ]:
inp_sample='running through the valley'
##%%
def next_word(inp_sample):
  inp_seq=tokenizer.texts_to_sequences([inp_sample])
  pd_inp_seq=pad_sequences(inp_seq,maxlen=maxlen-1,padding='pre')
  print(pd_inp_seq)
  y_proba=model.predict(pd_inp_seq)
  print('y_proba.shape',y_proba.shape)
  y_pred=np.argmax(y_proba,axis=-1)
  print('y_pred.shape',y_pred.shape)
  print('y_pred',y_pred)
  print('y_pred[0]',y_pred[0])
  # tf.random.categorical()
  nxt_w=tokenizer.index_word[y_pred[0]]
  return nxt_w

# next_word(inp_sample)
##%%
def extend_word(inp_sample,n=2):
  for _ in range(n):
    print('inp_sample',inp_sample)
    inp_sample += ' '+next_word(inp_sample)
    print('next_word',next_word)
    print('inp_sample',inp_sample)

extend_word(inp_sample,50)

In [42]:
# from tensorflow.keras.layers import TextVectorization

# token_layer=TextVectorization(max_tokens=vocab_size,output_sequence_length=int(percntl_train_95))

In [45]:
# token_layer.adapt(x_train_jn)
# #%%
# token_layer.get_vocabulary()[:10]
# #%% md
#  generated vocab size:

# token_layer.vocabulary_size()

# #%%
# vocab_size_embed_ly=token_layer.vocabulary_size()
# #%%
# import random

# rndm_sen=random.choice(x_train_jn)

# len_rndm_sen=len(rndm_sen.split())
# print(len_rndm_sen)
# print(rndm_sen)

# token_layer([rndm_sen])

63
their shared laughter had cleared a tension between ali and he . he felt more comfortable in her presence now , if still very aware of her . both sal and ali looked more relaxed too . he decided the laughter must have helped clear some of the impact of their recent drugged experiences . he glanced at sal , then turned to


<tf.Tensor: shape=(1, 93), dtype=int64, numpy=
array([[  103,  1519,  1293,    29,  1203,     6,  1365,   197,  6336,
            5,     9,     9,   167,    76,   843,    13,    14,  1274,
           71,    45,   122,   144,  1864,     8,    14,   187,  4787,
            5,  6336,    77,    76,  1959,   109,     9,   421,     2,
         1293,   174,    36,   760,   669,    94,     8,     2,  3793,
            8,   103,  4880,  5825, 10951,     9,   356,    20,  4787,
           55,   115,     3,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0]])>

In [28]:
y_train_spl=[y for (x,y) in tr_np_splt]

In [29]:
y_train_spl[:2]

['ayden', 'dress']

## without splitting the last word, We could use the whole sentence and use the word generation?

In [ ]:
from tensorflow.keras import Sequential,Model
from tensorflow.keras.layers import Dense,Embedding,Bidirectional,LSTM,Conv1D,GlobalMaxPooling1D,GlobalAveragePooling1D,Input

In [ ]:
# tr_np_sp=tr_np.split()

In [ ]:
# for item in train_set_sup.take(1):
#   print(item['passage'].numpy())

#   spl=item['passage'].numpy().split()

# print(spl)


In [ ]:
# def fnc(ds_i):
#   sn=ds_i['passage'].numpy().decode('UTF-8').split()
#   return sn[:-1], sn[-1]

In [ ]:
# for item in train_set_sup.take(1):
  # print(fnc(item))

In [ ]:
# list(train_set_sup.as_numpy_iterator())

## ds.map should not use non tensorflow fnc...eg. using .numpy() causes error "AttributeError: 'SymbolicTensor' object has no attribute 'numpy'"

In [ ]:
# print(tf.executing_eagerly())
# 
# 
# ds=train_set_sup
# # ds=train_set_sup.map(lambda it:tf.py_function(fun=fnc(it),inp=(1,),Tout=tf.float32))
# # ds=train_set_sup.map(lambda it:it['passage'].numpy().decode('UTF-8').split())
# ds=train_set_sup.map(fnc)
# 
# 
# # for item in ds.take(1):
# #   print(fnc(item))
# 
# 
# 
# 
